### ISSUE TITLE
Sass instruction work well in App but not in Addon

### ISSUE THREAD

**Issue by Swizz** [aexmachina/ember-cli-sass#120]
Hi,

I am faced with something really weird.
I am tying evolve the [ember-bulma](https://github.com/open-tux/ember-bulma) add-on to a sass import version like [ember-cli-foundation-sass](https://github.com/artificialio/ember-cli-foundation-sass).

Everything could working well unless one thing.

I have already used bulma sass with ember-cli-sass from scratch and everything goes OK. But when I use it inside an addon, only one line of the bulma source make it just crash.

```sass
.header-item > a:not(.button)
```

I really do not know why this specific line break it only in addon.

**Comment by Swizz** [comment]
I finally found the guilty.

In my ember-app the node-sass version used is `3.4.2` and in the recent addon the version is `3.5.3`.

So I force to fallback into the first one version and everything work well, right now.

**Comment by Swizz** [comment]
May be linked to [aexmachina/broccoli-sass-source-maps/issues/19](https://github.com/aexmachina/broccoli-sass-source-maps/issues/19)

**Comment by mike-north** [comment]
@aexmachina - I think you have hundreds of people hitting this error now. Due to the crash happening inside native code, inside a node-gyp wrapper, inside a broccoli plugin, inside an ember addon, it's extremely difficult for a novice developer to troubleshoot and track down. 

My suggestion is that, per aexmachina/broccoli-sass-source-maps/issues/19 you roll back the supported node-sass version so there's an easy and conventional path forward (i.e., install the addon and you're good to go, for all versions of node.js that ember-cli officially supports).

**Comment by aexmachina** [comment]
Thanks @mike-north, but the solution to this issue is to [specify which version of node-sass to use](https://github.com/aexmachina/ember-cli-sass#choosing-the-version-of-node-sass) until the underlying issue is fixed.
