### ISSUE TITLE
Where did v6.0.0 come from?

### ISSUE THREAD

**Issue by kellyselden** [aexmachina/ember-cli-sass#146]
There are no new commits or releases here. Did it come from a fork? Or are the commits and tag not pushed?

**Comment by xomaczar** [comment]
@kellyselden I believe @aexmachina just forgot to commit his changes before publishing to npm. Needs to be fixed.

**Comment by srvance** [comment]
And it causes my build to segfault.

**Comment by aexmachina** [comment]
I've pushed to Github now. It's not uncommon for different platforms to have some issues with a new node-sass major version - that's why I bump the major version of ember-cli-sass when node-sass is upgraded.

You can just stick on v5 until they've fixed the issues in node-sass. You should probably check that your issue is posted on node-sass too.

**Comment by srvance** [comment]
What's the best way to provide some diagnostic information? It didn't leave a node.debug.log or a core file (on macOS).
