### ISSUE TITLE
Incompatible with ember-css-modules

### ISSUE THREAD

**Issue by stephencarr** [aexmachina/ember-cli-sass#147]
Installing eslint results in compile failing:

```
Error: File not found: /app/styles/app.scss
in any of the following include paths:
```

A fresh app with latest `ember-cli-sass` works fine. When `ember-css-modules` is installed the above error occurs. Would be nice to have both play well with each other.

**Comment by aexmachina** [comment]
This is likely to be an issue with `ember-css-modules`.

**Comment by josenberg** [comment]
@aexmachina I believe that the bug is in the ember-cli-sass.

The [https://github.com/aexmachina/ember-cli-sass/blob/2dd0d0db601b1ab8a8c3630c75a797664263b207/index.js#L20](`/app/styles/`) is hard coded in the index.

What you think about the passing the include as an option (like the includePaths)?

[https://github.com/aexmachina/ember-cli-sass/blob/2dd0d0db601b1ab8a8c3630c75a797664263b207/index.js#L20](`/app/styles/`)

**Comment by aexmachina** [comment]
@josenberg, what would you pass as the value for that option when using ember-css-modules?

**Comment by josenberg** [comment]
I think that `/app/styles/` should be the default options, but would be nice if we could pass any value.

**Comment by aexmachina** [comment]
Yes, I'm trying to understand what you would pass when using ember-css-modules?

**Comment by josenberg** [comment]
I wanted to change the `includePaths` because the addon `ember-css-modules` 'hijack' the `app/styles` to its conventions. I needed to make sure that code that was written before with ember-cli-sass would continues working. 

But you is right, the 'wrong' behavior was in the  `ember-css-modules`, i found a way to solve this with an additional addon called [ember css modules sass](https://github.com/dfreeman/ember-css-modules-sass).

(sorry for the delay in my response)

**Comment by aexmachina** [comment]
Nicely done! Thanks for sorting it out 👍

**Comment by aexmachina** [comment]
Maybe we should add a note to the README? What would it say?
